AWSTemplateFormatVersion: '2010-09-09'
Description: Slack reminder using cloudwatch event + AWS Lambda function + slack api
Outputs:
  ReminderSlackBotFunctionArn:
    Description: Reminder Slack Reminder Function ARN
    Value:
      Fn::GetAtt:
      - ReminderSlackBotFunction
      - Arn
Parameters:
  ChannelId:
    Description: TargetChannelId
    Type: String
  SlackToken:
    Description: Slack auth token for using slack api
    Type: String
Resources:
  LogGroup:
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${ReminderSlackBotFunction}
      RetentionInDays: 14
    Type: AWS::Logs::LogGroup
  ReminderSlackBotFunction:
    Properties:
      CodeUri: s3://slack-reminder/32c911abf04d73101188d46f35a4ab03
      Description: Lambda function for notifing something to slack channel at specific
        time
      Environment:
        Variables:
          AUTH_TOKEN:
            Fn::Sub: Bearer ${SlackToken}
          CHANNEL_ID:
            Ref: ChannelId
      Events:
        ScheduleEvent:
          Properties:
            # リマインドを行いたい時間に設定する *GMTなので日本時間に合わせるには +9 する→10amにしたいなら1に設定する
            # 例1 : 平日の朝9時にリマインドしたい場合 cron(0 0 ? * MON-FRI *)
            # 例2 : 毎週金曜の13時にリマインドしたい場合 cron(0 4 ? * FRI *)
            Schedule: cron(0 0 ? * MON-FRI *)
          Type: Schedule
      FunctionName: RemindGoForward  # 被らない関数名に設定
      Handler: index.handler
      Runtime: nodejs12.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
