AWSTemplateFormatVersion: '2010-09-09'
Description: Slack reminder using cloudwatch event + AWS Lambda function + slack api
Outputs:
  ReminderSlackBotFunctionArn:
    Description: Reminder Slack Reminder Function ARN
    Value:
      Fn::GetAtt:
      - ReminderSlackBotFunction
      - Arn
Parameters:
  ChannelId:
    Description: TargetChannelId
    Type: String
  SlackToken:
    Description: Slack auth token for using slack api
    Type: String
Resources:
  LogGroup:
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${ReminderSlackBotFunction}
      RetentionInDays: 14
    Type: AWS::Logs::LogGroup
  ReminderSlackBotFunction:
    Properties:
      CodeUri: s3://ec2-sample/330ff13e83138a9e1a9383560b3ee537
      Description: Lambda function for notifing something to slack channel at specific
        time
      Environment:
        Variables:
          AUTH_TOKEN:
            Fn::Sub: Bearer ${SlackToken}
          CHANNEL_ID:
            Ref: ChannelId
      Events:
        ShecduleEvent:
          Properties:
            Schedule: cron(0 14 * ? * 2-6) # リマインドを行いたい時間に設定する
          Type: Schedule
      FunctionName: ReminderSlackBotFunction # 被らない関数名を使用する
      Handler: index.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
