AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Slack reminder using cloudwatch event + AWS Lambda function + slack api 

Parameters:
  SlackToken: 
    Type: String
    Description: Slack auth token for using slack api
  ChannelId: 
    Type: String
    Description: TargetChannelId

Resources:
    ReminderSlackBotFunction:
        Type: AWS::Serverless::Function 
        Properties:
            FunctionName: RemindAyuTodo # 被らない関数名にする
            Description: Lambda function for notifing something to slack channel at specific time 
            CodeUri: src/
            Handler: index.handler
            Runtime: nodejs12.x
            Environment: 
                Variables:
                    AUTH_TOKEN: !Sub Bearer ${SlackToken}
                    CHANNEL_ID: !Ref ChannelId
            Events:
                ScheduleEvent:
                    Type: Schedule 
                    Properties:
                        # リマインドを行いたい時間に設定する *GMTなので日本時間に合わせるには +9 する→10amにしたいなら1に設定する
                        # 例1 : 平日の朝9時にリマインドしたい場合 cron(0 0 ? * MON-FRI *)
                        # 例2 : 毎週金曜の13時にリマインドしたい場合 cron(0 4 ? * FRI *)
                        Schedule: "cron(0 0 ? * MON-FRI *)" # cron format

    LogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Sub /aws/lambda/${ReminderSlackBotFunction}
            RetentionInDays: 14
    
Outputs:
    ReminderSlackBotFunctionArn:
        Description: "Reminder Slack Reminder Function ARN"
        Value: !GetAtt ReminderSlackBotFunction.Arn
